### ISSUE TITLE
Formatting on Facebook (has P tags in it)

### ISSUE THREAD

**Issue by ghost** [kylewm/KnownIndieSyndicate#2]
I'm not sure if this should be here at KnownIndieSyndicate or on the Silo.Pub list.

I added my Facebook account for testing to IndieSyndicate on my Known site. When I post a **status update** all goes fine, but when I post a photo or post, the body of the post has P tags in it:
![2016-03-07_195306](https://cloud.githubusercontent.com/assets/546983/13579517/3a2f3d94-e49e-11e5-85d0-e2257781b71a.png)

I have Facebook now set to Social Media (see screenshot below), but I tested "default" as well which gives the exact same behavior.

![2016-03-07_195334](https://cloud.githubusercontent.com/assets/546983/13579597/9f4824ca-e49e-11e5-9fd6-0c22bbc11e5e.png)

**Comment by karadaisy** [comment]
This is the right place and that's definitely a bug, thanks! I will work on a fix.
